# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for hello-spring-boot-rest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file hello-spring-boot-rest/pom.xml
  
  deployDev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: deploy to dev
      run: echo "deploy to dev"
  
  deployProd:
    runs-on: ubuntu-latest
    environment: prod
    env: # Or as an environment variable
      az_credentials_secret: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
    - name: Azure Login
      run: echo "az login using $az_credentials_secret" 
     
